spring:
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: sa
    password: ''
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

build:
  name: Cards Service
  version: d1
  profile: DEFAULT