spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cards:3306/cardsdb
    username: root
    password: root
    sql:
      init:
        mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace

build:
  name: Cards Service
  version: d1
  profile: DEFAULT